name: *!Solo Leveling: ReAwakening (2024) ğ™µullğ™¼ovie Downlğš˜ad Frğše 1080ğš™\720ğš™\480ğš™ Hğ™³ HIğ™½DI Dubğš‹ed Filğ™¼yzğš’lla Isaidub
description: This is an action to assign yourself to an issue for a repo you are not a contributor to.
author: Brian Douglas
branding:
  icon: 'thumbs-up'
  color: 'white'
runs:
  using: 'docker'
  image: 'Dockerfile'
